### ISSUE TITLE
[ISSUE] Texture Clamping

### ISSUE THREAD

**Issue by Alyng0** [qqrz997/CustomSabersLite#1]
Some Saber Creators maybe have forgotten to clamp the texture in unity whích makes it tile, if distorted

**Comment by qqrz997** [comment]
with the currently implementation, setting the texture to clamp appears to have no effect on tiled trails. i've thought about this and decided not to fix it, at least for now. 

the reason being is that - if people are going to use this to test their sabers - i would rather they correct their mistakes rather than having the mod correct their mistakes for them. this is unfortunate for the many sabers out there that have this issue, but i believe that has happened because of what i mentioned.

**Comment by Alyng0** [comment]
I didnt say to make it permantly clamp textures, sry for not adding it to the message.
I meant to make i a toggle, just like in SF, if people are gonna test their sabers in this mod then they can just turn it off.
But for people who just want to play with them it would be great to have toggle to fix the issue.
