### ISSUE TITLE
A glowing line appears at the end of the trail

### ISSUE THREAD

**Issue by rynan4818** [qqrz997/CustomSabersLite#28]
When using a specific Saber model, a glowing line appears at the end of the trail.

### Saber models
https://modelsaber.com/Sabers/?id=1558510617&pc

### Tested with BeatSaber 1.38.0 and CustomSabersLite 0.12.7
![image](https://github.com/user-attachments/assets/a8e62872-4231-42b7-95f7-a87ec563b59e)

### SaberFactory for BeatSaber 1.29.1 displays correctly as shown.
![image](https://github.com/user-attachments/assets/22f3baee-5087-40e2-8268-02bf03d00037)

**Comment by qqrz997** [comment]
### this is an issue with the saber

SaberFactory has a **setting** that clamps the texture on a custom trail, this has caused a long, hidden problem. CustomSabersLite will **not** have any settings to correct mistakes made by saber creators so that they will create sabers for longevity.

since SaberFactory has been around for most of the game's lifespan, a large quantity of sabers were **created and tested with specific settings in SaberFactory.** this is bad design on SaberFactory's part, as it means that not every saber is properly configured by default.

it may become possible in a future version of CustomSabersLite to customize your saber with another saber's custom trail. i am hoping that will minimize this problem, whilst not covering up improper configuration of sabers.

**Comment by rynan4818** [comment]
I see! I understand.

https://mdotamaan.github.io/BeatSaber-CustomTrailsGuide/#Trail%20Material

So the reason is that the `Wrap Mode` is set to `Repeat` instead of `Clamp` in `Setting Up The Trail Material`.

The model I'm actually using is a private one, so I'd like to try either modifying the original model or making a mod to forcibly set Texture.wrapMode to Clamp.

**Comment by rynan4818** [comment]
I created a mod that applies a patch and confirmed that the problem was solved.

https://github.com/rynan4818/CustomSabersLiteTextureWrapClampPatch

If possible, I would like to consider modifying the original model.
